### ISSUE TITLE
maven引入不了dtjava,访问404,如何解决

### ISSUE THREAD

**Issue by Chenshuai770** [tingyugetc520/dtjava-demo#1]
Could not transfer artifact com.github.tingyugetc520:dt-java:pom:0.0.1-SNAPSHOT from/to github-dt-java-repo (https://tingyugetc520.github.io/DtJava/maven-repo/): Transfer failed for https://tingyugetc520.github.io/DtJava/maven-repo/com/github/tingyugetc520/dt-java/0.0.1-SNAPSHOT/dt-java-0.0.1-SNAPSHOT.pom

**Comment by tingyugetc520** [comment]
这个问题我已经发现了，在GitHub被墙了之后是有问题的，正在解决，准备将dtjava放在中央仓库里面去，之后国内的maven镜像就能拉过来了

**Comment by tingyugetc520** [comment]
DtJava已经发布到了中央仓库，版本为0.1.2，华为云的镜像已经拉过来了，你可以pull下代码看下

**Comment by Chenshuai770** [comment]
还是不行
Cannot resolve com.github.tingyugetc520:dt-java:0.1.2







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "tingyugetc520"<notifications@github.com&gt;; 
发送时间: 2021年3月8日(星期一) 下午4:11
收件人: "tingyugetc520/dtjava-demo"<dtjava-demo@noreply.github.com&gt;; 
抄送: "我心依旧"<770456288@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tingyugetc520/dtjava-demo] maven引入不了dtjava,访问404,如何解决 (#1)





 
DtJava已经发布到了中央仓库，版本为0.1.2，华为云的镜像已经拉过来了，你可以pull下代码看下

**Comment by tingyugetc520** [comment]
https://repo.huaweicloud.com/repository/maven/com/github/tingyugetc520/dt-java/0.1.2/dt-java-0.1.2.pom
这个地址打不开么

**Comment by tingyugetc520** [comment]
目前是没问题的，我将关闭这个issue了
